import { Geist, Geist_Mono, Homenaje } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const homenje = Homenaje({
  subsets: ["latin"],
  weight: "400"
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${homenje.className} antialiased flex flex-col max-h-screen`}>
        <header className="">
          <nav className="flex justify-center bg-purple-500 p-5 w-full">
            <ul className="flex justify-center gap-10 text-white text-xl">
              <li>
                <a className="hover:text-black" href="#home">home</a>
              </li>
              <li>
                <a className="hover:text-black" href="#workex">experience</a>
              </li>
              <li>
                <a className="hover:text-black" href="#skills">skills</a>
              </li>
              <li>
                <a className="hover:text-black" href="#projects">projects</a>
              </li>
              <li>
                <a className="hover:text-black" href="#contact">contact</a>
              </li>
            </ul>
          </nav>

        </header>
        {children}
      {/* <footer className="static">
        <div className="bg-blue-400">
          i am foot
        </div>
      </footer> */}
      </body>
    </html>
  );
}
